baseurl = "https://minshain.github.io"
title = "Welcome Minshain's Blog"
theme = "cleanwhite"
languageCode = "zh-tw"
# Enable comments by entering your Disqus shortname
disqusShortname = "minshain"
googleAnalytics = "UA-160833467-1"
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/home-bg-jeep.jpg"
  SEOTitle = "銘祥的部落客 | Minshain's Blog"
  description = "陳銘祥,遊民，好爸爸，生活探險家 | 這裡是 陳銘祥 的部落客，紀錄一些生活小事與心得。"
  keyword = "陳銘祥, minshain, 陳銘祥的部落客, 安先生, Minshain Blog, 部落客, 電子電路, Internet, Web"
  slogan = "I hear I forget， I see I remember， I do I understand"

  image_404 = "img/404-bg.jpg"
  title_404 = "ERROR 404 It may something worry."
  omit_categories = false

  # leancloud storage for page view counter
  page_view_conter = false 
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  # 無法啟用 nmp run algolia ，可能是找不到algolia.json的問題，但Hugo後有\public\algolia.json
  algolia_search = false 
  algolia_appId = "10BHTYD2R2"
  algolia_indexName = "minshain"
  algolia_apiKey = "1225dd21cd57c002dde03aef8955d66b"

  # Sidebar settings
  sidebar_about_description = "Software Developer, Open Source Enthusiast and Life Adventurer"
  #sidebar_avatar = "img/avatar-zhaohuabing.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`
  sidebar_avatar = "img/minshain.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 1 

  # Baidu Analytics
  ba_track_id = ""
  
  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  disqus_proxy = ""
  disqus_site = ""

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  reward = false 
  # reward_guide = "如果这篇文章对你有用,请随意打赏" 

  friends = true
  bookmarks = false
  about_me = true

  # Include any custom CSS and/or JS files, url or relative to /static folder
  #custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/main.css"]
  #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

  [params.social]
  rss            = true 
  email          = "minshain@gmail.com"
  #facebook      = "https://www.facebook.com/minshain"
  #googleplus    = "full profile url in googleplus"
  twitter       = "https://twitter.com/minshain"
  linkedin       = "https://www.linkedin.com/in/chen-minshain-3176b197/"
  #stackoverflow  = "https://stackoverflow.com/users/yourstackoverflowid"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/minshain"
  #wechat         = "your wechat qr code image"
 #medium         = "full profile url in medium"
  #pinterest     = "full profile url in pinterest"
  #reddit        = "full profile url in reddit"
  #gitlab        = "full profile url in gitlab"
  #mastodon      = "full profile url in mastodon"
  #keybase       = "full profile url in keybase"
  #xing          = "https://www.xing.com/profile/yourxingid"
  #git           = "full profile url for git user"
  
  [[params.friend_link]]
  title = "安梅的FACEBOOK"
  href =  "https://www.facebook.com/profile.php?id=100000066947007m"

  [[params.bookmark_link]]
  title =  "Martin Fowler"
  href =  "https://martinfowler.com"
  [[params.bookmark_link]]
  title = "ServiceMesher"
  href =  "http://www.servicemesher.com"
  [[params.bookmark_link]]
  title =  "Pxhere"
  href = "https://pxhere.com"
  [[params.bookmark_link]]
  title = "unsplash"
  href = "https://unsplash.com"
  
  [[params.addtional_menus]]
  title =  "BOOKS"
  href =  "/top/books/"
  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
